
  name: CI

  on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

  jobs:
    build:
      runs-on: ubuntu-latest

      #env:
        #DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
        #DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

      steps:
        - uses: actions/checkout@v4
        - name: Set up Kotlin
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'

        - name: Set up Gradle
          uses: gradle/actions/setup-gradle@v4

        - name:
          run: ./gradlew build

        - name: Run tests
          run: ./gradlew test

  
