name: JwtCI

env:
  PROJECT_ID: 'cicdtest-438007'
  REGION: 'europe-north1'
  SERVICE: 'javathesis23'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/775853616903/locations/global/workloadIdentityPools/github/providers/javathesis'
  SERVICE_ACCOUNT: 'github-actions-sa@cicdtest-438007.iam.gserviceaccount.com'

on:
  push:
    paths: [ 'jwt/**' ]
  pull_request:
    paths: [ 'jwt/**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kotlin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        run: ./gradlew :jwt:test
        continue-on-error: false

      - name: Build JWT Jar
        run: ./gradlew :jwt:build

      - name: List files
        run: ls -R

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/775853616903/locations/global/workloadIdentityPools/github/providers/javathesis'
          service_account: 'github-actions-sa@cicdtest-438007.iam.gserviceaccount.com'

      - name: Check Credentials File
        run: ls -l "${GOOGLE_APPLICATION_CREDENTIALS}"

      - name: Verify authentication
        run: gcloud auth list

      - name: Debug Access Token
        run: echo "${{ steps.auth.outputs.auth_token }}"

      # BEGIN - Docker auth and build
      #
      # If you already have a container image, you can omit these steps.
      - name: 'Docker Auth'
        uses: 'docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567' # docker/login-action@v3
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: '${{ env.REGION }}-docker.pkg.dev'

      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build -f jwt/Dockerfile --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"