
name: JwtCI

on:
  push:
    paths: [ 'jwt/**' ]
  pull_request:
    paths: [ 'jwt/**' ]

jobs:
  build:
    runs-on: ubuntu-latest

      #env:
      #DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      #DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Kotlin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        run: ./gradlew :jwt:test


